### ISSUE TITLE
Example does not work with Ubunut 20.04

### ISSUE THREAD

**Issue by RamiSiadous** [aegirhall/console-menu#44]
Got an error message when running an example app in out of the box Ubuntu 20.04 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python3.8/site-packages/consolemenu/console_menu.py", line 169, in _wrap_start
    self._main_loop()
  File "/root/.local/lib/python3.8/site-packages/consolemenu/console_menu.py", line 225, in _main_loop
    self.draw()
  File "/root/.local/lib/python3.8/site-packages/consolemenu/console_menu.py", line 232, in draw
    self.screen.printf(self.formatter.format(title=self.title, subtitle=self.subtitle, items=self.items,
  File "/root/.local/lib/python3.8/site-packages/consolemenu/screen.py", line 74, in printf
    print(*args, end='')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 3-77: ordinal not in range(256)

Although maybe it is related to python3.8 that is automatically comes with that distro

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"

**Comment by ParkerK** [comment]
This is Python 3.8 related, as I have the same issue when running the example on 3.8 on Windows

**Comment by RamiSiadous** [comment]
after setting the border style to ASCII the problem went away
set_border_style_type(MenuBorderStyleType.ASCII_BORDER)
something is not working well with encoding of frames in Ubuntu

**Comment by aegirhall** [comment]
Thanks for the tip @RamiSiadous, I'll have to spin up 20.04 and take a look.
